# --- General settings ---
# Auto-save every 15 minutes, auto-restore on tmux start
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Hook to save previous sessions then kill the tmux server on detach
set-hook -g client-detached 'run-shell "tmux-resurrect save && tmux kill-server"'
