schemaVersion = 1

[[comboMode.bindings]]
key = 'o'
label = 'Teams'
url = 'tuna://run/path.%252FApplications%252FMicrosoft%2520Teams.app/Open'

[[comboMode.bindings]]
key = 'i'
label = 'Email'
url = 'tuna://run/TunaCore.SystemApplicationsCatalog.Mail/Open'

[[comboMode.bindings]]
key = 'y'
label = 'Spotify'
url = 'tuna://run/path.%252FApplications%252FSpotify.app/Open'

[[comboMode.bindings]]
key = 'c'
label = 'Code'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.T3%20Code%20(Nightly)/Open'

[[comboMode.bindings]]
key = 'x'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.OpenCode/Open'

[[comboMode.bindings]]
iconPath = '/Applications/Obsidian.app'
key = 'n'
label = 'Notes'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Obsidian/Open'

[[comboMode.bindings]]
key = 'e'
label = 'Emoji'
url = 'tuna://run/url.raycast:%252F%252Fextensions%252Fraycast%252Femoji-symbols%252Fsearch-emoji-symbols/Open%20URL'

[[comboMode.bindings]]
iconPath = '/Applications/WezTerm.app'
key = 'enter'
label = 'Ghostty'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Ghostty/Open'

[[comboMode.bindings]]
iconPath = 'arrow.uturn.backward.square.fill'
key = 'tab'
label = 'Previous Workspace'
url = 'tuna://run/text.yabai%2520-m%2520space%2520--focus%2520recent/Run%20Text%20as%20Shell%20Command'

[[comboMode.bindings]]
key = 'f'
label = 'Yazi (Finder)'
url = 'tuna://run/text.wezterm%2520start%2520--%2520zsh%2520-ic%2520y/Run%20Text%20as%20Shell%20Command'

[[comboMode.bindings]]
key = 't'
label = 'Messages'
url = 'tuna://run/path.%252FSystem%252FApplications%252FMessages.app/Open'

[[comboMode.bindings]]
key = 'b'
label = 'Browser'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Zen%20Browser/Open'

[[comboMode.bindings]]
key = 'u'
label = 'Claude'
url = 'tuna://run/TunaCore.AllApplicationsCatalog.Claude/Open'

[[comboMode.bindings]]
key = 's'
label = 'Shelf'
url = 'tuna://run/Tuna.Internal.ShelfCatalog.Shelf/Tuna.BasicActionsCatalog.Show'

[[comboMode.bindings]]
key = 'l'
label = 'Launch New Window'

    [[comboMode.bindings.children]]
    iconPath = '/Applications/Zen Browser.app'
    key = 'b'
    label = 'Browser'
    url = 'tuna://run/text.open%2520-n%2520%2522%252FApplications%252FZen%2520Browser.app%2522/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    iconPath = '/Applications/DBeaver.app'
    key = 'd'
    label = 'DBeaver'
    url = 'tuna://run/text.open%2520-n%2520%2522%252FApplications%252FDBeaver.app%2522/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    iconPath = '/Applications/WezTerm.app'
    key = 'enter'
    label = 'WezTerm'
    url = 'tuna://run/text.open%2520-n%2520%2522%252FApplications%252FWezTerm.app%2522/Run%20Text%20as%20Shell%20Command'

    [[comboMode.bindings.children]]
    iconPath = '/System/Applications/Freeform.app'
    key = 'f'
    label = 'Freeform'
    url = 'tuna://run/text.open%2520-n%2520%2522%252FSystem%252FApplications%252FFreeform.app%2522/Run%20Text%20as%20Shell%20Command'

[[comboMode.bindings]]
key = 'm'
label = 'App Menu'
url = 'tuna://run/text.omniwmctl%2520command%2520open-menu-anywhere/Run%20Text%20as%20Shell%20Command'

[[comboMode.bindings]]
key = 'w'
label = 'Window Menu'
url = 'tuna://run/text.omniwmctl%2520command%2520open-command-palette/Run%20Text%20as%20Shell%20Command'

[[comboMode.bindings]]
key = 'B'
label = 'Toggle Blur'
url = 'tuna://run/text.open%2520%2522monocle:%252F%252Ftoggle%2522/Run%20Text%20as%20Shell%20Command'

[hotkeys]
custom = []

    [hotkeys.app.comboMode]
    carbonKeyCode = 49
    carbonModifiers = 6912

    [hotkeys.app.dictation]
    carbonKeyCode = 9
    carbonModifiers = 2048

[settings]
comboModeThemeStyle = 'breadcrumb'
themeIdentifier = 'com.brnbw.tuna.themes.NormieBar'

[[catalogSettings]]
catalogIdentifier = 'com.brnbw.tuna.themes.default'

    [catalogSettings.values]
    ThemeTint = 'system'