set -g @plugin 'vaaleyard/tmux-dotbar'

# Config
set -g @tmux-dotbar-position 'top'

# supposing you use catppuccin moccha
# set -g @tmux-dotbar-bg "#1e1e2e"
# set -g @tmux-dotbar-fg "#585b70"
# set -g @tmux-dotbar-fg-current "#cdd6f4"
# set -g @tmux-dotbar-fg-prefix "#cba6f7"
# set -g @tmux-dotbar-fg-session "#9399b2"

# Everforest Dark Colors
# set-option -g @tmux-dotbar-bg "#2d353b"
# set-option -g @tmux-dotbar-fg "#7a8478"
# set-option -g @tmux-dotbar-fg-current "#d3c6aa"
# set-option -g @tmux-dotbar-fg-prefix "#d699b6"
# set-option -g @tmux-dotbar-fg-session "#a7c080"

# GitHub Dark Default Colors
set-option -g @tmux-dotbar-bg "#0d1117"
set-option -g @tmux-dotbar-fg "#7d8590"
set-option -g @tmux-dotbar-fg-current "#e6edf3"
set-option -g @tmux-dotbar-fg-prefix "#2f81f7"
set-option -g @tmux-dotbar-fg-session "#76e3ea"

# Dracula Colors
# set-option -g @tmux-dotbar-bg "#282a36"
# set-option -g @tmux-dotbar-fg "#6272a4"
# set-option -g @tmux-dotbar-fg-current "#f8f8f2"
# set-option -g @tmux-dotbar-fg-prefix "#ff79c6"
# set-option -g @tmux-dotbar-fg-session "#bd93f9"

set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
